import { Currency, CurrencyMap } from "@models/currency"
import { IModalListInDto } from "react-native-picker-modal-view/dist/Interfaces"

export const CURRENCIES: Currency[] = [
  {
    symbol: "$",
    name: "US Dollar",
    symbolNative: "$",
    code: "USD",
    image: require("./flags/USD.png"),
  },
  {
    symbol: "\u20aa",
    name: "Israeli New Sheqel",
    symbolNative: "\u20aa",
    code: "ILS",
    image: require("./flags/ILS.png"),
  },
  {
    symbol: "\u20ac",
    name: "Euro",
    symbolNative: "\u20ac",
    code: "EUR",
    image: require("./flags/EUR.png"),
  },
  {
    symbol: "CA$",
    name: "Canadian Dollar",
    symbolNative: "$",
    code: "CAD",
    image: require("./flags/CAD.png"),
  },
  {
    symbol: "AED",
    name: "United Arab Emirates Dirham",
    symbolNative: "\u062f.\u0625.\u200f",
    code: "AED",
    image: require("./flags/AED.png"),
  },
  {
    symbol: "Af",
    name: "Afghan Afghani",
    symbolNative: "\u060b",
    code: "AFN",
    image: require("./flags/AFN.png"),
  },
  {
    symbol: "ALL",
    name: "Albanian Lek",
    symbolNative: "Lek",
    code: "ALL",
    image: require("./flags/ALL.png"),
  },
  {
    symbol: "AMD",
    name: "Armenian Dram",
    symbolNative: "\u0564\u0580.",
    code: "AMD",
    image: require("./flags/AMD.png"),
  },
  {
    symbol: "AR$",
    name: "Argentine Peso",
    symbolNative: "$",
    code: "ARS",
    image: require("./flags/ARS.png"),
  },
  {
    symbol: "AU$",
    name: "Australian Dollar",
    symbolNative: "$",
    code: "AUD",
    image: require("./flags/AUD.png"),
  },
  {
    symbol: "man.",
    name: "Azerbaijani Manat",
    symbolNative: "\u043c\u0430\u043d.",
    code: "AZN",
    image: require("./flags/AZN.png"),
  },
  {
    symbol: "KM",
    name: "Bosnia-Herzegovina Convertible Mark",
    symbolNative: "KM",
    code: "BAM",
    image: require("./flags/BAM.png"),
  },
  {
    symbol: "Tk",
    name: "Bangladeshi Taka",
    symbolNative: "\u09f3",
    code: "BDT",
    image: require("./flags/BDT.png"),
  },
  {
    symbol: "BGN",
    name: "Bulgarian Lev",
    symbolNative: "\u043b\u0432.",
    code: "BGN",
    image: require("./flags/BGN.png"),
  },
  {
    symbol: "BD",
    name: "Bahraini Dinar",
    symbolNative: "\u062f.\u0628.\u200f",
    code: "BHD",
    image: require("./flags/BHD.png"),
  },
  {
    symbol: "FBu",
    name: "Burundian Franc",
    symbolNative: "FBu",
    code: "BIF",
    image: require("./flags/BIF.png"),
  },
  {
    symbol: "BN$",
    name: "Brunei Dollar",
    symbolNative: "$",
    code: "BND",
    image: require("./flags/BND.png"),
  },
  {
    symbol: "Bs",
    name: "Bolivian Boliviano",
    symbolNative: "Bs",
    code: "BOB",
    image: require("./flags/BOB.png"),
  },
  {
    symbol: "R$",
    name: "Brazilian Real",
    symbolNative: "R$",
    code: "BRL",
    image: require("./flags/BRL.png"),
  },
  {
    symbol: "BWP",
    name: "Botswanan Pula",
    symbolNative: "P",
    code: "BWP",
    image: require("./flags/BWP.png"),
  },
  {
    symbol: "BZ$",
    name: "Belize Dollar",
    symbolNative: "$",
    code: "BZD",
    image: require("./flags/BZD.png"),
  },
  {
    symbol: "CDF",
    name: "Congolese Franc",
    symbolNative: "FrCD",
    code: "CDF",
    image: require("./flags/CDF.png"),
  },
  {
    symbol: "CHF",
    name: "Swiss Franc",
    symbolNative: "CHF",
    code: "CHF",
    image: require("./flags/CHF.png"),
  },
  {
    symbol: "CL$",
    name: "Chilean Peso",
    symbolNative: "$",
    code: "CLP",
    image: require("./flags/CLP.png"),
  },
  {
    symbol: "CN\u00a5",
    name: "Chinese Yuan",
    symbolNative: "CN\u00a5",
    code: "CNY",
    image: require("./flags/CNY.png"),
  },
  {
    symbol: "CO$",
    name: "Colombian Peso",
    symbolNative: "$",
    code: "COP",
    image: require("./flags/COP.png"),
  },
  {
    symbol: "\u20a1",
    name: "Costa Rican Col\u00f3n",
    symbolNative: "\u20a1",
    code: "CRC",
    image: require("./flags/CRC.png"),
  },
  {
    symbol: "CV$",
    name: "Cape Verdean Escudo",
    symbolNative: "CV$",
    code: "CVE",
    image: require("./flags/CVE.png"),
  },
  {
    symbol: "K\u010d",
    name: "Czech Republic Koruna",
    symbolNative: "K\u010d",
    code: "CZK",
    image: require("./flags/CZK.png"),
  },
  {
    symbol: "Fdj",
    name: "Djiboutian Franc",
    symbolNative: "Fdj",
    code: "DJF",
    image: require("./flags/DJF.png"),
  },
  {
    symbol: "Dkr",
    name: "Danish Krone",
    symbolNative: "kr",
    code: "DKK",
    image: require("./flags/DKK.png"),
  },
  {
    symbol: "RD$",
    name: "Dominican Peso",
    symbolNative: "RD$",
    code: "DOP",
    image: require("./flags/DOP.png"),
  },
  {
    symbol: "DA",
    name: "Algerian Dinar",
    symbolNative: "\u062f.\u062c.\u200f",
    code: "DZD",
    image: require("./flags/DZD.png"),
  },
  {
    symbol: "EGP",
    name: "Egyptian Pound",
    symbolNative: "\u062c.\u0645.\u200f",
    code: "EGP",
    image: require("./flags/EGP.png"),
  },
  {
    symbol: "Nfk",
    name: "Eritrean Nakfa",
    symbolNative: "Nfk",
    code: "ERN",
    image: require("./flags/ERN.png"),
  },
  {
    symbol: "Br",
    name: "Ethiopian Birr",
    symbolNative: "Br",
    code: "ETB",
    image: require("./flags/ETB.png"),
  },
  {
    symbol: "\u00a3",
    name: "British Pound Sterling",
    symbolNative: "\u00a3",
    code: "GBP",
    image: require("./flags/GBP.png"),
  },
  {
    symbol: "GEL",
    name: "Georgian Lari",
    symbolNative: "GEL",
    code: "GEL",
    image: require("./flags/GEL.png"),
  },
  {
    symbol: "GH\u20b5",
    name: "Ghanaian Cedi",
    symbolNative: "GH\u20b5",
    code: "GHS",
    image: require("./flags/GHS.png"),
  },
  {
    symbol: "FG",
    name: "Guinean Franc",
    symbolNative: "FG",
    code: "GNF",
    image: require("./flags/GNF.png"),
  },
  {
    symbol: "GTQ",
    name: "Guatemalan Quetzal",
    symbolNative: "Q",
    code: "GTQ",
    image: require("./flags/GTQ.png"),
  },
  {
    symbol: "HK$",
    name: "Hong Kong Dollar",
    symbolNative: "$",
    code: "HKD",
    image: require("./flags/HKD.png"),
  },
  {
    symbol: "HNL",
    name: "Honduran Lempira",
    symbolNative: "L",
    code: "HNL",
    image: require("./flags/HNL.png"),
  },
  {
    symbol: "kn",
    name: "Croatian Kuna",
    symbolNative: "kn",
    code: "HRK",
    image: require("./flags/HRK.png"),
  },
  {
    symbol: "Ft",
    name: "Hungarian Forint",
    symbolNative: "Ft",
    code: "HUF",
    image: require("./flags/HUF.png"),
  },
  {
    symbol: "Rp",
    name: "Indonesian Rupiah",
    symbolNative: "Rp",
    code: "IDR",
    image: require("./flags/IDR.png"),
  },
  {
    symbol: "Rs",
    name: "Indian Rupee",
    symbolNative: "\u099f\u0995\u09be",
    code: "INR",
    image: require("./flags/INR.png"),
  },
  {
    symbol: "IQD",
    name: "Iraqi Dinar",
    symbolNative: "\u062f.\u0639.\u200f",
    code: "IQD",
    image: require("./flags/IQD.png"),
  },
  {
    symbol: "IRR",
    name: "Iranian Rial",
    symbolNative: "\ufdfc",
    code: "IRR",
    image: require("./flags/IRR.png"),
  },
  {
    symbol: "Ikr",
    name: "Icelandic Kr\u00f3na",
    symbolNative: "kr",
    code: "ISK",
    image: require("./flags/ISK.png"),
  },
  {
    symbol: "J$",
    name: "Jamaican Dollar",
    symbolNative: "$",
    code: "JMD",
    image: require("./flags/JMD.png"),
  },
  {
    symbol: "JD",
    name: "Jordanian Dinar",
    symbolNative: "\u062f.\u0623.\u200f",
    code: "JOD",
    image: require("./flags/JOD.png"),
  },
  {
    symbol: "\u00a5",
    name: "Japanese Yen",
    symbolNative: "\uffe5",
    code: "JPY",
    image: require("./flags/JPY.png"),
  },
  {
    symbol: "Ksh",
    name: "Kenyan Shilling",
    symbolNative: "Ksh",
    code: "KES",
    image: require("./flags/KES.png"),
  },
  {
    symbol: "KHR",
    name: "Cambodian Riel",
    symbolNative: "\u17db",
    code: "KHR",
    image: require("./flags/KHR.png"),
  },
  {
    symbol: "CF",
    name: "Comorian Franc",
    symbolNative: "FC",
    code: "KMF",
    image: require("./flags/KMF.png"),
  },
  {
    symbol: "\u20a9",
    name: "South Korean Won",
    symbolNative: "\u20a9",
    code: "KRW",
    image: require("./flags/KRW.png"),
  },
  {
    symbol: "KD",
    name: "Kuwaiti Dinar",
    symbolNative: "\u062f.\u0643.\u200f",
    code: "KWD",
    image: require("./flags/KWD.png"),
  },
  {
    symbol: "KZT",
    name: "Kazakhstani Tenge",
    symbolNative: "\u0442\u04a3\u0433.",
    code: "KZT",
    image: require("./flags/KZT.png"),
  },
  {
    symbol: "LB\u00a3",
    name: "Lebanese Pound",
    symbolNative: "\u0644.\u0644.\u200f",
    code: "LBP",
    image: require("./flags/LBP.png"),
  },
  {
    symbol: "SLRs",
    name: "Sri Lankan Rupee",
    symbolNative: "SL Re",
    code: "LKR",
    image: require("./flags/LKR.png"),
  },
  {
    symbol: "Lt",
    name: "Lithuanian Litas",
    symbolNative: "Lt",
    code: "LTL",
    image: require("./flags/LTL.png"),
  },
  {
    symbol: "LD",
    name: "Libyan Dinar",
    symbolNative: "\u062f.\u0644.\u200f",
    code: "LYD",
    image: require("./flags/LYD.png"),
  },
  {
    symbol: "MAD",
    name: "Moroccan Dirham",
    symbolNative: "\u062f.\u0645.\u200f",
    code: "MAD",
    image: require("./flags/MAD.png"),
  },
  {
    symbol: "MDL",
    name: "Moldovan Leu",
    symbolNative: "MDL",
    code: "MDL",
    image: require("./flags/MDL.png"),
  },
  {
    symbol: "MGA",
    name: "Malagasy Ariary",
    symbolNative: "MGA",
    code: "MGA",
    image: require("./flags/MGA.png"),
  },
  {
    symbol: "MKD",
    name: "Macedonian Denar",
    symbolNative: "MKD",
    code: "MKD",
    image: require("./flags/MKD.png"),
  },
  {
    symbol: "MMK",
    name: "Myanma Kyat",
    symbolNative: "K",
    code: "MMK",
    image: require("./flags/MMK.png"),
  },
  {
    symbol: "MOP$",
    name: "Macanese Pataca",
    symbolNative: "MOP$",
    code: "MOP",
    image: require("./flags/MOP.png"),
  },
  {
    symbol: "MURs",
    name: "Mauritian Rupee",
    symbolNative: "MURs",
    code: "MUR",
    image: require("./flags/MUR.png"),
  },
  {
    symbol: "MX$",
    name: "Mexican Peso",
    symbolNative: "$",
    code: "MXN",
    image: require("./flags/MXN.png"),
  },
  {
    symbol: "RM",
    name: "Malaysian Ringgit",
    symbolNative: "RM",
    code: "MYR",
    image: require("./flags/MYR.png"),
  },
  {
    symbol: "MTn",
    name: "Mozambican Metical",
    symbolNative: "MTn",
    code: "MZN",
    image: require("./flags/MZN.png"),
  },
  {
    symbol: "N$",
    name: "Namibian Dollar",
    symbolNative: "N$",
    code: "NAD",
    image: require("./flags/NAD.png"),
  },
  {
    symbol: "\u20a6",
    name: "Nigerian Naira",
    symbolNative: "\u20a6",
    code: "NGN",
    image: require("./flags/NGN.png"),
  },
  {
    symbol: "C$",
    name: "Nicaraguan C\u00f3rdoba",
    symbolNative: "C$",
    code: "NIO",
    image: require("./flags/NIO.png"),
  },
  {
    symbol: "Nkr",
    name: "Norwegian Krone",
    symbolNative: "kr",
    code: "NOK",
    image: require("./flags/NOK.png"),
  },
  {
    symbol: "NPRs",
    name: "Nepalese Rupee",
    symbolNative: "\u0928\u0947\u0930\u0942",
    code: "NPR",
    image: require("./flags/NPR.png"),
  },
  {
    symbol: "NZ$",
    name: "New Zealand Dollar",
    symbolNative: "$",
    code: "NZD",
    image: require("./flags/NZD.png"),
  },
  {
    symbol: "OMR",
    name: "Omani Rial",
    symbolNative: "\u0631.\u0639.\u200f",
    code: "OMR",
    image: require("./flags/OMR.png"),
  },
  {
    symbol: "S/.",
    name: "Peruvian Nuevo Sol",
    symbolNative: "S/.",
    code: "PEN",
    image: require("./flags/PEN.png"),
  },
  {
    symbol: "\u20b1",
    name: "Philippine Peso",
    symbolNative: "\u20b1",
    code: "PHP",
    image: require("./flags/PHP.png"),
  },
  {
    symbol: "PKRs",
    name: "Pakistani Rupee",
    symbolNative: "\u20a8",
    code: "PKR",
    image: require("./flags/PKR.png"),
  },
  {
    symbol: "z\u0142",
    name: "Polish Zloty",
    symbolNative: "z\u0142",
    code: "PLN",
    image: require("./flags/PLN.png"),
  },
  {
    symbol: "\u20b2",
    name: "Paraguayan Guarani",
    symbolNative: "\u20b2",
    code: "PYG",
    image: require("./flags/PYG.png"),
  },
  {
    symbol: "QR",
    name: "Qatari Rial",
    symbolNative: "\u0631.\u0642.\u200f",
    code: "QAR",
    image: require("./flags/QAR.png"),
  },
  {
    symbol: "RON",
    name: "Romanian Leu",
    symbolNative: "RON",
    code: "RON",
    image: require("./flags/RON.png"),
  },
  {
    symbol: "din.",
    name: "Serbian Dinar",
    symbolNative: "\u0434\u0438\u043d.",
    code: "RSD",
    image: require("./flags/RSD.png"),
  },
  {
    symbol: "RUB",
    name: "Russian Ruble",
    symbolNative: "\u0440\u0443\u0431.",
    code: "RUB",
    image: require("./flags/RUB.png"),
  },
  {
    symbol: "RWF",
    name: "Rwandan Franc",
    symbolNative: "FR",
    code: "RWF",
    image: require("./flags/RWF.png"),
  },
  {
    symbol: "SR",
    name: "Saudi Riyal",
    symbolNative: "\u0631.\u0633.\u200f",
    code: "SAR",
    image: require("./flags/SAR.png"),
  },
  {
    symbol: "Skr",
    name: "Swedish Krona",
    symbolNative: "kr",
    code: "SEK",
    image: require("./flags/SEK.png"),
  },
  {
    symbol: "S$",
    name: "Singapore Dollar",
    symbolNative: "$",
    code: "SGD",
    image: require("./flags/SGD.png"),
  },
  {
    symbol: "Ssh",
    name: "Somali Shilling",
    symbolNative: "Ssh",
    code: "SOS",
    image: require("./flags/SOS.png"),
  },
  {
    symbol: "SY\u00a3",
    name: "Syrian Pound",
    symbolNative: "\u0644.\u0633.\u200f",
    code: "SYP",
    image: require("./flags/SYP.png"),
  },
  {
    symbol: "\u0e3f",
    name: "Thai Baht",
    symbolNative: "\u0e3f",
    code: "THB",
    image: require("./flags/THB.png"),
  },
  {
    symbol: "DT",
    name: "Tunisian Dinar",
    symbolNative: "\u062f.\u062a.\u200f",
    code: "TND",
    image: require("./flags/TND.png"),
  },
  {
    symbol: "T$",
    name: "Tongan Pa\u02bbanga",
    symbolNative: "T$",
    code: "TOP",
    image: require("./flags/TOP.png"),
  },
  {
    symbol: "TL",
    name: "Turkish Lira",
    symbolNative: "TL",
    code: "TRY",
    image: require("./flags/TRY.png"),
  },
  {
    symbol: "TT$",
    name: "Trinidad and Tobago Dollar",
    symbolNative: "$",
    code: "TTD",
    image: require("./flags/TTD.png"),
  },
  {
    symbol: "NT$",
    name: "New Taiwan Dollar",
    symbolNative: "NT$",
    code: "TWD",
    image: require("./flags/TWD.png"),
  },
  {
    symbol: "TSh",
    name: "Tanzanian Shilling",
    symbolNative: "TSh",
    code: "TZS",
    image: require("./flags/TZS.png"),
  },
  {
    symbol: "\u20b4",
    name: "Ukrainian Hryvnia",
    symbolNative: "\u20b4",
    code: "UAH",
    image: require("./flags/UAH.png"),
  },
  {
    symbol: "USh",
    name: "Ugandan Shilling",
    symbolNative: "USh",
    code: "UGX",
    image: require("./flags/UGX.png"),
  },
  {
    symbol: "$U",
    name: "Uruguayan Peso",
    symbolNative: "$",
    code: "UYU",
    image: require("./flags/UYU.png"),
  },
  {
    symbol: "UZS",
    name: "Uzbekistan Som",
    symbolNative: "UZS",
    code: "UZS",
    image: require("./flags/UZS.png"),
  },
  {
    symbol: "Bs.F.",
    name: "Venezuelan Bol\u00edvar",
    symbolNative: "Bs.F.",
    code: "VEF",
    image: require("./flags/VEF.png"),
  },
  {
    symbol: "\u20ab",
    name: "Vietnamese Dong",
    symbolNative: "\u20ab",
    code: "VND",
    image: require("./flags/VND.png"),
  },
  {
    symbol: "FCFA",
    name: "CFA Franc BEAC",
    symbolNative: "FCFA",
    code: "XAF",
    image: require("./flags/XAF.png"),
  },
  {
    symbol: "CFA",
    name: "CFA Franc BCEAO",
    symbolNative: "CFA",
    code: "XOF",
    image: require("./flags/XOF.png"),
  },
  {
    symbol: "YR",
    name: "Yemeni Rial",
    symbolNative: "\u0631.\u064a.\u200f",
    code: "YER",
    image: require("./flags/YER.png"),
  },
  {
    symbol: "R",
    name: "South African Rand",
    symbolNative: "R",
    code: "ZAR",
    image: require("./flags/ZAR.png"),
  },
]

export const DropdownCurrencies = (): IModalListInDto<Currency>[] =>
  CURRENCIES.map(curr => ({ Id: curr.code, Name: curr.name, Value: curr }))

export const CurrenciesMap = (): CurrencyMap => {
  const currencyMap: CurrencyMap = {}
  CURRENCIES.forEach(
    value =>
      (currencyMap[value.code] = {
        image: value.image,
        name: value.name,
        symbol: value.symbol,
      }),
  )
  return currencyMap
}
